# This is a basic workflow to help you get started with Actions

name: How to manually trigger a workflow

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Your GitHub username'
        required: true
      reason:
        description: 'Why are you running this workflow ?'
        required: true
        default: 'I am running test before implementing an automated workflow'

jobs:
  tests_manual_workflow:
    runs-on: ubuntu-latest
    steps:
      - run: >
          echo "User ${{github.event.inputs.username}} ran a workflow manually."
          echo "Because ${{github.event.reason}}."
